## NumPy
Answer the following questions

### Create an Array
1. Create a 4X2 integer array and print its attributes.

  The element must be a type of unsigned int16

In [1]:
import numpy as np
from numpy import *

NumArray = np.array([2,3,5,7,22,43,41,66], dtype='int16')
NumArray = NumArray.reshape(4, 2)

print("4X2 Integer Array")
print(NumArray)
print("\n ******** \n")
print("Data Type:")
print(NumArray.dtype)

4X2 Integer Array
[[ 2  3]
 [ 5  7]
 [22 43]
 [41 66]]

 ******** 

Data Type:
int16


### Slice an Array

2. Create a 5 rows by 4 columns numpy array of random float32 numbers and extract an array of odd rows and even columns from the numpy array.

In [2]:
NumArray = random.rand(5, 4)
NumArray = NumArray.astype(float32)
print(NumArray.round(4))
NumArray.dtype

[[0.8207 0.3652 0.172  0.1304]
 [0.5291 0.3    0.9551 0.116 ]
 [0.7842 0.2447 0.682  0.3028]
 [0.6145 0.2999 0.1012 0.1627]
 [0.0564 0.3284 0.3185 0.6949]]


dtype('float32')

In [3]:
#NumArrayOddRow = NumArray[::2]
#print(NumArrayOdd)

In [4]:
#NumArrayEvenCol = NumArray[:, 1::2]
#print(NumArrayEvenCol)

In [5]:
NumArrayEvenRowOddCol = NumArray[::2, 1::2]
print(NumArrayEvenRowOddCol)

[[0.3651531  0.13035114]
 [0.24470253 0.30275318]
 [0.32843414 0.69488645]]


### 2D Array Manipulation

3. Create a two dimensional array of dimension 4 rows by 5 columns with random integers and replace all the values of the second column of the array with value 5.

In [6]:
NumArrayInt=random.randint(1000, size=(4,5))
NumArrayInt[:,1]=5
NumArrayInt

array([[762,   5, 927, 942, 627],
       [624,   5,   9, 955, 850],
       [735,   5, 364, 962, 681],
       [675,   5, 627, 832,  45]])

### Array Operations

4. Add two numpy arrays of random int16 values and take square of each of the element of the resulting array.

In [7]:
NumArrayInt1=random.randint(20, size=(10)).astype(int16)
NumArrayInt2=random.randint(20, size=(10)).astype(int16)
print(NumArrayInt1)
print(NumArrayInt2)
NumArrayIntAdd=NumArrayInt1+NumArrayInt2
print("----------")
print(NumArrayIntAdd)
NumArrayIntSquare=np.square(NumArrayIntAdd)
print("----------")
print(NumArrayIntSquare)


[14 14 14  0  6 19 19 15 13  2]
[13 11 19  9  7 10 16 12  4  5]
----------
[27 25 33  9 13 29 35 27 17  7]
----------
[ 729  625 1089   81  169  841 1225  729  289   49]


### Array of Random Numbers

5. Generate two numpy lists of 20 random integers each. Create a new numpy list containing odd numbers from the first list and even numbers from the second list.

In [8]:
NumArrayInt1=random.randint(100, size=(20))
NumArrayInt2=random.randint(100, size=(20))


OddNumbers = NumArrayInt1[NumArrayInt1%2==1]
EvenNumbers = NumArrayInt2[NumArrayInt2%2==0]

print(NumArrayInt1)
print(OddNumbers)
print("------------------")
print(NumArrayInt2)
print(EvenNumbers)
print("------New List-----")

NewListOddEven=np.concatenate((OddNumbers, EvenNumbers))
print(NewListOddEven)

[31 83 41 91 63 19  5 51 76 85 94 37 25 62 75  2 18 27 67 74]
[31 83 41 91 63 19  5 51 85 37 25 75 27 67]
------------------
[22 48 64 99 11 57 35 75 44 54 17 74 16 34 92 53  4 97 27  3]
[22 48 64 44 54 74 16 34 92  4]
------New List-----
[31 83 41 91 63 19  5 51 85 37 25 75 27 67 22 48 64 44 54 74 16 34 92  4]


# Data Manipulation using Pandas


We will use the dataset from https://archive.ics.uci.edu/ml/datasets/bank+marketing for this assignment. 

You will click on the data folder link to download bank.zip file.

### Data IO
a. Unzip the **bank.zip** file.

b. Upload **bank.csv** on github.

c. Import the file using url on github in a DataFrame named **bank**.

d. Note that the delimiter is a semi-colon and not comma.

In [9]:
import os
import pandas as pd
from pandas import DataFrame

gitHubFile ='https://raw.githubusercontent.com/sumitraju/data-science/main/data_manipulation_using_pandas_numpy/data/bank.csv'

bank = pd.read_csv(gitHubFile, sep=';')
bank.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [10]:
bank.shape

(4521, 17)

### Magic Command

a. Create a new folder named **data** in Google Colab. Use magic command **mkdir**.

b. Create a copy of DataFrame in the new folder as **bank01.csv**

In [11]:
!mkdir data

bank.to_csv('./data/bank01.csv')

A subdirectory or file data already exists.


## DataFrame Subsetting

a. Extract a DataFrame of records with **management** and **entrepreneur** job category only.

In [12]:
DataFrameJob = bank.loc[(bank['job'] == 'management') | (bank['job'] == 'entrepreneur')]
DataFrameJob.shape

(1137, 17)

In [13]:

DataFrameJob.describe(include='object')

job  marital education default housing  loan   contact month  \
count         1137     1137      1137    1137    1137  1137      1137  1137   
unique           2        3         4       2       2     2         3    12   
top     management  married  tertiary      no     yes    no  cellular   may   
freq           969      689       860    1116     597   976       816   279   

       poutcome     y  
count      1137  1137  
unique        4     2  
top     unknown    no  
freq        928   991