## NumPy
Answer the following questions

### Create an Array
1. Create a 4X2 integer array and print its attributes.

  The element must be a type of unsigned int16

In [ ]:
import numpy as np
from numpy import *

NumArray = np.array([2,3,5,7,22,43,41,66], dtype='int16')
NumArray = NumArray.reshape(4, 2)

print("4X2 Integer Array")
print(NumArray)
print("\n ******** \n")
print("Data Type:")
print(NumArray.dtype)

4X2 Integer Array
[[ 2  3]
 [ 5  7]
 [22 43]
 [41 66]]

 ******** 

Data Type:
int16


### Slice an Array

2. Create a 5 rows by 4 columns numpy array of random float32 numbers and extract an array of odd rows and even columns from the numpy array.

In [ ]:
NumArray = random.rand(5, 4)
NumArray = NumArray.astype(float32)
print(NumArray.round(4))
NumArray.dtype

[[0.8555 0.3528 0.73   0.252 ]
 [0.7006 0.588  0.2372 0.1038]
 [0.7872 0.5305 0.3324 0.6107]
 [0.487  0.0159 0.1681 0.0944]
 [0.4737 0.3549 0.4798 0.4423]]


dtype('float32')

In [ ]:
#NumArrayOddRow = NumArray[::2]
#print(NumArrayOdd)

In [ ]:
#NumArrayEvenCol = NumArray[:, 1::2]
#print(NumArrayEvenCol)

In [ ]:
NumArrayEvenRowOddCol = NumArray[::2, 1::2]
print(NumArrayEvenRowOddCol)

[[0.3528118  0.25195724]
 [0.53049105 0.61068285]
 [0.3548543  0.442345  ]]


### 2D Array Manipulation

3. Create a two dimensional array of dimension 4 rows by 5 columns with random integers and replace all the values of the second column of the array with value 5.

In [ ]:
NumArrayInt=random.randint(1000, size=(4,5))
NumArrayInt[:,1]=5
NumArrayInt

array([[606,   5, 243, 179, 487],
       [913,   5, 968, 687, 217],
       [648,   5, 337, 388, 747],
       [769,   5,  46, 253, 190]])

### Array Operations

4. Add two numpy arrays of random int16 values and take square of each of the element of the resulting array.

In [ ]:
NumArrayInt1=random.randint(20, size=(10)).astype(int16)
NumArrayInt2=random.randint(20, size=(10)).astype(int16)
print(NumArrayInt1)
print(NumArrayInt2)
NumArrayIntAdd=NumArrayInt1+NumArrayInt2
print("----------")
print(NumArrayIntAdd)
NumArrayIntSquare=np.square(NumArrayIntAdd)
print("----------")
print(NumArrayIntSquare)


[10  3  7 12  0 17 13 12 15  0]
[13 14 17  6  5 18 19  8  3 15]
----------
[23 17 24 18  5 35 32 20 18 15]
----------
[ 529  289  576  324   25 1225 1024  400  324  225]


### Array of Random Numbers

5. Generate two numpy lists of 20 random integers each. Create a new numpy list containing odd numbers from the first list and even numbers from the second list.

In [ ]:
NumArrayInt1=random.randint(100, size=(20))
NumArrayInt2=random.randint(100, size=(20))


OddNumbers = NumArrayInt1[NumArrayInt1%2==1]
EvenNumbers = NumArrayInt2[NumArrayInt2%2==0]

print(NumArrayInt1)
print(OddNumbers)
print("------------------")
print(NumArrayInt2)
print(EvenNumbers)
print("------New List-----")

NewListOddEven=np.concatenate((OddNumbers, EvenNumbers))
print(NewListOddEven)

[68 70 71 48 43 38 68 84 46  5 90 30 64 43 70 75 30  8 88 23]
[71 43  5 43 75 23]
------------------
[ 9 32 16 34 45  1 41 99 80 64 19  1  0 68 28 28 73 83 23 40]
[32 16 34 80 64  0 68 28 28 40]
------New List-----
[71 43  5 43 75 23 32 16 34 80 64  0 68 28 28 40]


# Data Manipulation using Pandas


We will use the dataset from https://archive.ics.uci.edu/ml/datasets/bank+marketing for this assignment. 

You will click on the data folder link to download bank.zip file.

### Data IO
a. Unzip the **bank.zip** file.

b. Upload **bank.csv** on github.

c. Import the file using url on github in a DataFrame named **bank**.

d. Note that the delimiter is a semi-colon and not comma.

In [ ]:
import os
import pandas as pd
from pandas import DataFrame

gitHubFile ='https://raw.githubusercontent.com/sumitraju/BA2-Class/main/Class-2/Bank/bank.csv'

bank = pd.read_csv(gitHubFile, sep=';')
bank.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [ ]:
bank.shape

(4521, 17)

### Magic Command

a. Create a new folder named **data** in Google Colab. Use magic command **mkdir**.

b. Create a copy of DataFrame in the new folder as **bank01.csv**

In [ ]:
!mkdir data

bank.to_csv('./data/bank01.csv')

## DataFrame Subsetting

a. Extract a DataFrame of records with **management** and **entrepreneur** job category only.

In [ ]:
DataFrameJob = bank.loc[(bank['job'] == 'management') | (bank['job'] == 'entrepreneur')]
DataFrameJob.shape

(1137, 17)

In [ ]:

DataFrameJob.describe(include='object')

job  marital education default  ...   contact month poutcome     y
count         1137     1137      1137    1137  ...      1137  1137     1137  1137
unique           2        3         4       2  ...         3    12        4     2
top     management  married  tertiary      no  ...  cellular   may  unknown    no
freq           969      689       860    1116  ...       816   279      928   991

[4 rows x 10 columns]